export const LOCATION_DATA = [
  {
    locationId: 1,
    locationTypeId: "Private",
    cityId: "New Westminister",
    name: "Lowe´s",
    postalCode: "V3M 0G2",
    address: "1085 ﻿Tanaka Ct",
    phone: "604-527-7239",
    latitude: 49.188678,
    longitude: -122.951498,
    openingHour: "Call for hours of operation",
    website: "https://www.lowes.ca/services/recycling-centre",
    imageUrl: "",
    locationNotes:
      "Minimize your impact on the environment by bringing your paint, batteries, lightbulbs, and fluorescent tubes to one of Lowe's Recycling Centres for safe disposal.",
  },
  {
    locationId: 2,
    locationTypeId: "Private",
    cityId: "New Westminister",
    name: "Bridgeview Bottle & Depot",
    postalCode: "3V 8C3",
    address: "Unit 118-12332 Pattullo Place",
    phone: "604-587-5557",
    latitude: 49.203894,
    longitude: -122.880924,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/bridgeview-return-it-depot/?",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 3,
    locationTypeId: "Private",
    cityId: "New Westminster",
    name: "Queensborough Landing Depot",
    postalCode: "V3M 5K2",
    address: "Unit A - 409 Boyne Street",
    phone: "604-540-4467",
    latitude: 49.193645,
    longitude: -122.940826,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/queensborough/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 4,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "Yaletown Express",
    postalCode: "V6B 3G7",
    address: "1387 Richards Street",
    phone: "604-336-7206",
    latitude: 49.274256,
    longitude: -123.12662,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/yaletown-return-it-express/",
    imageUrl: "",
    locationNotes:
      "During this time, please allow up to 10 business days for your updated account balance to appear online after dropping off your Express bags.",
  },
  {
    locationId: 5,
    locationTypeId: "Government",
    cityId: "Vancouver",
    name: "Regional Recycling - Vancouver",
    postalCode: "V6A 2L2",
    address: "960 Evans Avenue",
    phone: "855-701-7171",
    latitude: 49.270918,
    longitude: -123.082132,
    openingHour: "7 Days a Week, 9:00am - 5:00pm.",
    website: "https://www.regionalrecycling.ca/vancouver-recycling-depot/",
    imageUrl: "",
    locationNotes:
      "Full Deposit Bottle Return. Free Scrap Metal Recycling. Recycle Electronics for FREE! Clean Family Friendly Depot.",
  },
  {
    locationId: 6,
    locationTypeId: "Non-profit",
    cityId: "Vancouver",
    name: "United We Can Bottle Depot",
    postalCode: "V6A 2P3",
    address: "449 Industrial Avenue",
    phone: "604-681-0001",
    latitude: 49.269812,
    longitude: -123.093759,
    openingHour: "Monday - Sunday, 8:00am - 6:00pm.",
    website: "http://www.unitedwecan.ca/",
    imageUrl: "",
    locationNotes:
      "United We Can is a Vancouver based non-profit organization that creates economic opportunities through environmental initiatives for people living in the Downtown Eastside. It was created by locals for locals who rely on recycling refundable beverage containers as their source of income.",
  },
  {
    locationId: 7,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "Powell Street Bottle Depot",
    postalCode: "V5L 1H9",
    address: "1856 Powell Street",
    phone: "604-253-4987",
    latitude: 49.28451,
    longitude: -123.065943,
    openingHour: "Monday - Sunday, 9:00am - 6:00pm.",
    website: "https://powell-street-return-it-bottle.business.site/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 8,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "East Van Bottle Depot",
    postalCode: "V5X 3R9",
    address: "2605 Kaslo Street",
    phone: "604-255-4243",
    latitude: 49.261267,
    longitude: -123.046649,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "http://www.bcbottledepot.com/our-locations/east-van/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 9,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "Vancouver Central Depot",
    postalCode: "V5R 5H4",
    address: "2639 Kingsway",
    phone: "604-434-0707",
    latitude: 49.239159,
    longitude: -123.05052,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website:
      "https://www.return-it.ca/locations/vancouver-central-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 10,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "South Van Bottle Depot",
    postalCode: "V5X 4K6",
    address: "34 East 69th Avenue",
    phone: "604-325-3370",
    latitude: 49.209004,
    longitude: -123.105771,
    openingHour: "Monday - Saturday, 8:30am - 5:30pm.",
    website: "http://www.bcbottledepot.com/our-locations/south-van/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 11,
    locationTypeId: "Private",
    cityId: "Vancouver",
    name: "West Depot",
    postalCode: "V6P 3G4",
    address: "1253 West 75th Avenue",
    phone: "604-263-8809",
    latitude: 49.202656,
    longitude: -123.132933,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website:
      "https://marpolevillage.ca/business/vancouver-west-return-it-depot/",
    imageUrl: " ",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 12,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Brentwood Depot",
    postalCode: "V5C 3T4",
    address: "3931 Graveley Street",
    phone: "604-294-2827",
    latitude: 49.270727,
    longitude: -123.016826,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/brentwood-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 13,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Collingwood Bottle Exchange",
    postalCode: "V5H 1Y4",
    address: "3805 Kingsway",
    phone: "604-437-1926",
    latitude: 49.232928,
    longitude: -123.018968,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/collingwood-bottle-exchange",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 14,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Metrotown Centre Depot",
    postalCode: "V5J 1C2",
    address: "4760 Imperial Street",
    phone: "604-451-8888",
    latitude: 49.221954,
    longitude: -122.995656,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website:
      "https://www.bbb.org/ca/bc/burnaby/profile/bottle-return/metrotown-return-it-centre-0037-1213803",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 15,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Lee's Bottle Depot",
    postalCode: "V5J 4S6",
    address: "7385 Buller Avenue",
    phone: "604-435-3432",
    latitude: 49.216589,
    longitude: -122.977682,
    openingHour: "Tuesday - Suday, 10:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/lees-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 16,
    locationTypeId: "Government",
    cityId: "Burnaby",
    name: "Regional Recycling - Burnaby",
    postalCode: "V5B 3A9",
    address: "2876 Norland Avenue",
    phone: "855-701-7171",
    latitude: 49.25848,
    longitude: -122.977327,
    openingHour: "7 Days a Week, 9:00am - 5:00pm.",
    website: "https://www.regionalrecycling.ca/burnaby-recycling-depot/",
    imageUrl: "",
    locationNotes:
      "Full Deposit Bottle Return. Free Scrap Metal Recycling. Recycle Electronics for FREE! Clean Family Friendly Depot.",
  },
  {
    locationId: 17,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Kensington Square Centre Depot",
    postalCode: "V5B 1S2",
    address: "6518 Hastings Street",
    phone: "604-299-9779",
    latitude: 49.27975,
    longitude: -122.967925,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/kensington-square-return-it/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 18,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "East Hastings Bottle Depot",
    postalCode: "V5B 1S9",
    address: "6893 Hastings Street",
    phone: "604-299-4254",
    latitude: 49.28065,
    longitude: -122.96099,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/east-hastings-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 19,
    locationTypeId: "Non-profit",
    cityId: "Burnaby",
    name: "SFU Burnaby - Express & GO",
    postalCode: "V5A 4Y6",
    address: "Cornerstone Mews and University Crescent",
    phone: "604-239-4334",
    latitude: 49.278227,
    longitude: -122.91925,
    openingHour: "Monday - Sunday, 7:00am - 10:00pm.",
    website:
      "sfu.ca/sfunews/stories/2019/11/sfu-welcomes-lower-mainlands-first-stand-alone-express---go-recy.html",
    imageUrl: "",
    locationNotes:
      "It’s located in a repurposed shipping container at SFU’s Burnaby campus in the East Parking lot just below UniverCity Town Square.",
  },
  {
    locationId: 20,
    locationTypeId: "Private",
    cityId: "Burnaby",
    name: "Edmonds Depot",
    postalCode: "V3N 1B2",
    address: "7496 Edmonds Street",
    phone: "604-527-0466",
    latitude: 49.221811,
    longitude: -122.944069,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/edmonds-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 21,
    locationTypeId: "Private",
    cityId: "Coquitlam",
    name: "North Road Depot",
    postalCode: "V3K 3V9",
    address: "Unit W - 435 North Road, Cariboo Shopping Centre",
    phone: "604-931-6098",
    latitude: 49.248164,
    longitude: -122.890666,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/north-road-return-depot/",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 22,
    locationTypeId: "Private",
    cityId: "Coquitlam",
    name: "Blue Mountain Bottle Depot",
    postalCode: "V3J 4P8",
    address: "511 Blue Mountain Street",
    phone: "604-939-7616",
    latitude: 49.250032,
    longitude: -122.868047,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/blue-mountain-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 23,
    locationTypeId: "Private",
    cityId: "Coquitlam",
    name: "Lougheed Depot",
    postalCode: "V3K 6N5",
    address: "1045A Lougheed Highway",
    phone: "778-397-5005",
    latitude: 49.236187,
    longitude: -122.866942,
    openingHour: "Tuesday - Saturday, 10:00am - 4:00pm.",
    website: "https://www.return-it.ca/locations/lougheed-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 24,
    locationTypeId: "Private",
    cityId: "New Westminster",
    name: "Sapperton Depot",
    postalCode: "V3L 3P2",
    address: "Unit 21 - 79 Braid Street",
    phone: "604-523-9699",
    latitude: 49.230786,
    longitude: -122.879352,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/sapperton-return-it-depot",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 25,
    locationTypeId: "Private",
    cityId: "New Westminster",
    name: "New West Bottle Depot",
    postalCode: "V3M 3T2",
    address: "916 - 8th Street",
    phone: "604-521-4018",
    latitude: 49.216288,
    longitude: -122.927676,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/new-west-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 26,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Semiahmoo Bottle Depot",
    postalCode: "V4A 2J4",
    address: "Unit 29, 15515 - 24th Avenue",
    phone: "604-531-7669",
    latitude: 49.047395,
    longitude: -122.791775,
    openingHour: "Tuesday - Saturday, 10:00am - 4:00pm.",
    website: "https://www.return-it.ca/locations/semiahmoo-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 27,
    locationTypeId: "Government",
    cityId: "Surrey",
    name: "Regional Recycling - Cloverdale",
    postalCode: "V3S 4C3",
    address: "5534 176th Street, Surrey",
    phone: "855-701-7171",
    latitude: 49.103253,
    longitude: -122.733862,
    openingHour: "7 Days a Week, 9:00am - 5:00pm.",
    website: "https://www.regionalrecycling.ca/cloverdale-recycling-depot/",
    imageUrl: "",
    locationNotes:
      "Full Deposit Bottle Return. Free Scrap Metal Recycling. Recycle Electronics for FREE! Clean Family Friendly Depot.",
  },
  {
    locationId: 28,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Bridgeview Bottle",
    postalCode: "V3V 8C3",
    address: "Unit 118-12332 Pattullo Place",
    phone: "604-587-5557",
    latitude: 49.203943,
    longitude: -122.880957,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/bridgeview-return-it-depot",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 29,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Sur-Del Bottle Depot",
    postalCode: "V3V 4H2",
    address: "8962 - 120A Street",
    phone: "604-837-0497",
    latitude: 49.16632,
    longitude: -122.888172,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.surdelbottledepot.ca/",
    imageUrl: "",
    locationNotes:
      "A staple in the Surrey community for more than 15 years, Sur-Del Bottle Depot (formerly Booze Brothers) has provided recycling services under our current ownership for nearly a decade.",
  },
  {
    locationId: 30,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Scott Road Bottle Depot",
    postalCode: "V3W 3H8",
    address: "Unit 2, 12111 - 86th Avenue",
    phone: "604-543-0606",
    latitude: 49.159959,
    longitude: -122.887295,
    openingHour: "7 Days a Week, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/scott-road-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 31,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Jenill Recycling",
    postalCode: "V4E 2X7",
    address: "Unit 1, 13140 88th Avenue",
    phone: "604-596-1751",
    latitude: 49.16219,
    longitude: -122.85854,
    openingHour: "Tuesday - Saturday, 10:00am - 4:00pm.",
    website: "https://www.return-it.ca/locations,jenill-recycling/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 32,
    locationTypeId: "Government",
    cityId: "Surrey",
    name: "Surrey Central Bottle Depot",
    postalCode: "V3T 1W7",
    address: "13845 - 104th Avenue",
    phone: "604-588-7790",
    latitude: 49.191903,
    longitude: -122.837873,
    openingHour: "Tuesday - Saturday, 10:00am - 4:00pm.",
    website: "https://www.regionalrecycling.ca/cloverdale-recycling-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 33,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Guildford Bottle Depot",
    postalCode: "V3R 1V9",
    address: "Unit 100, 14727 108A Avenue",
    phone: "604-588-4489",
    latitude: 49.199528,
    longitude: -122.813818,
    openingHour: "Tuesday - Saturday, 9:00am - 5:00pm.",
    website: "https://www.return-it.ca/locations/guildford-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 35,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Fleetwood Bottle Depot",
    postalCode: "V3R 3P2",
    address: "15093 Fraser Highway",
    phone: "604-585-3544",
    latitude: 49.167562,
    longitude: -122.803672,
    openingHour: "Tuesday - Sunday, 9:30am - 4:30pm.",
    website: "https://www.return-it.ca/locations/fleetwood-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 36,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "Newton Bottle Depot",
    postalCode: "V3W 4M4",
    address: "110 - 13245 72 Avenue",
    phone: "604-596-9266",
    latitude: 49.134412,
    longitude: -122.855019,
    openingHour: "Tuesday - Sunday, 10:00am - 4:00pm.",
    website: "https://www.return-it.ca/locations/newton-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 37,
    locationTypeId: "Non-profit",
    cityId: "Surrey",
    name: "Panorama Village Depot",
    postalCode: "V3S 9A5",
    address: "Unit 112-15157 Highway 10",
    phone: "604-579-0208",
    latitude: 49.105724,
    longitude: -122.801702,
    openingHour: "Tuesday - Sunday, 10:00am - 4:00pm.",
    website: "https://www.return-it.ca/locations/panorama-village-return-it/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 38,
    locationTypeId: "Government",
    cityId: "Surrey",
    name: "Regional Recycling - Cloverdale",
    postalCode: "V3S 4C3",
    address: "5534 176th Street",
    phone: "855-701-7171",
    latitude: 49.103176,
    longitude: -122.733754,
    openingHour: "7 Days a Week, 9:00am - 5:00pm.",
    website: "https://www.regionalrecycling.ca/cloverdale-recycling-depot/",
    imageUrl: "",
    locationNotes:
      "Full Deposit Bottle Return. Free Scrap Metal Recycling. Recycle Electronics for FREE! Clean Family Friendly Depot.",
  },
  {
    locationId: 39,
    locationTypeId: "Private",
    cityId: "Surrey",
    name: "White Rock Depot",
    postalCode: "V4P 2B1",
    address: "3221 140th Street",
    phone: "778-294-9919",
    latitude: 49.060487,
    longitude: -122.833901,
    openingHour: "Tuesday - Saturday, 9:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/white-rock-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 40,
    locationTypeId: "Private",
    cityId: "Richmond",
    name: "OK Bottle Depot",
    postalCode: "V6X 2A8",
    address: "145-5751 Cedarbridge Way",
    phone: "604-244-0008",
    latitude: 49.173334,
    longitude: -123.142027,
    openingHour: "Tuesday - Saturday, 10:00am - 6:00pm.",
    website: "https://www.return-it.ca/locations/ok-bottle-depot",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 41,
    locationTypeId: "Private",
    cityId: "Richmond",
    name: "Richmond Bottle Depot",
    postalCode: "V7E 5C8",
    address: "Unit 135, 8171 Westminster Highway",
    phone: "604-232-5555",
    latitude: 49.171054,
    longitude: -123.133845,
    openingHour: "Tuesday - Saturday, 8:30am - 1:00pm.",
    website:
      "https://www.return-it.ca/locations/richmond-return-it-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 42,
    locationTypeId: "Private",
    cityId: "Richmond",
    name: "Blundell Depot Centre",
    postalCode: "V7C 5K1",
    address: "130 - 8180 No. 2 Road",
    phone: "604-274-1999",
    latitude: 49.154246,
    longitude: -123.156356,
    openingHour: "Tuesday - Sunday, 9:30am - 4:30pm.",
    website: "https://www.return-it.ca/locations/blundell-return-it-centre",
    imageUrl: "",
    locationNotes:
      "At this location you can return both alcohol and non-alcohol aluminum beverage containers together for recycling.",
  },
  {
    locationId: 43,
    locationTypeId: "Private",
    cityId: "Richmond",
    name: "Ironwood Bottle Depot",
    postalCode: "V7A 4V5",
    address: "Unit 110-11020 Horseshoe Way",
    phone: "604-275-0585",
    latitude: 49.131002,
    longitude: -123.092094,
    openingHour: "Tuesday - Sunday, 10:00am - 5:00pm.",
    website:
      "https://www.return-it.ca/locations/ironwood-bottle-return-it-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 44,
    locationTypeId: "Private",
    cityId: "Ladner",
    name: "Ladner Bottle Depot",
    postalCode: "V4K 2Y1",
    address: "4930 Elliott Street",
    phone: "604-946-0309",
    latitude: 49.092454,
    longitude: -123.083796,
    openingHour: "Tuesday - Saturday, 9:30am - 5:00pm.",
    website: "https://www.return-it.ca/locations/ladner-bottle-depot/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 45,
    locationTypeId: "Private",
    cityId: "Tsawwassen",
    name: "Tsawwassen Depot Centre",
    postalCode: "V4L 1C4",
    address: "5636 12th Avenue",
    phone: "604-943-7661",
    latitude: 49.024649,
    longitude: -123.067255,
    openingHour: "Tuesday - Sunday, 9:30am - 4:00pm.",
    website: "https://www.return-it.ca/locations/tsawwassen-return-it-centre/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 46,
    locationTypeId: "Government",
    cityId: "Burnaby",
    name: "Burnaby Eco-Centre",
    postalCode: "V5C 6C6",
    address: "4855 Still Creek Driv",
    phone: "604-294-7972",
    latitude: 49.261571,
    longitude: -122.994612,
    openingHour: "Monday - Sunday: 8:00am to 4:00pm.",
    website:
      "https://www.burnaby.ca/City-Services/Garbage---Recycling/Eco-Centre.html",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 47,
    locationTypeId: "Private",
    cityId: "Richmond",
    name: "Richmond Recycling Depot",
    postalCode: "V7C 5B2",
    address: "5555 Lynas Ln, Richmond",
    phone: "604-276-4010",
    latitude: 49.172766,
    longitude: -123.165157,
    openingHour: "Tuesday - Sunday, 9:00am - 6:15pm.",
    website: "https://www.richmond.ca/services/recycling/recyclingdepot.htm",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
  {
    locationId: 48,
    locationTypeId: "Private",
    cityId: "Maple Ridge",
    name: "Ridge Meadows Recycling Society",
    postalCode: "V2W 1B7",
    address: "10092 236 St Unit 1",
    phone: "604-463-5545",
    latitude: 49.186392,
    longitude: -122.568251,
    openingHour: "Tuesday - Sunday, 8:00am - 5:00pm.",
    website: "https://rmrecycling.org/",
    imageUrl: "",
    locationNotes:
      "When returning your beverage containers, leave the caps on to ensure small plastic pieces are recycled.",
  },
];